### ISSUE TITLE
Komega fails to build with Intel MPI: USE mpi, ONLY : MPI_Allreduce rejected (regression from 5bee7b45)

### ISSUE THREAD

**Issue by k-yoshimi** [issp-center-dev/HPhi#291]
On `develop` (and any branch merged up to it), `src/komega/komega_math.F90` fails to compile with the Intel Fortran compiler + Intel MPI:

```
komega_math.F90(81): error #6580: Name in only-list does not exist or is not accessible.   [MPI_ALLREDUCE]
  USE mpi, ONLY : MPI_Allreduce, MPI_DOUBLE_PRECISION, MPI_SUM
```
(also lines 113, 151, 187).

**Cause:** commit `5bee7b45` ("Harden Komega MPI scalar reductions", 2026-07-16) introduced `USE mpi, ONLY : MPI_Allreduce, ...`. Intel MPI's `mpi` Fortran module exposes `MPI_Allreduce` as a generic interface that Intel Fortran does not allow to be named in an `ONLY` clause, so the build aborts. GNU Fortran + Open MPI accepts it, so the regression is invisible on gcc-based CI/hosts.

**Impact:** HPhi cannot be built with the Intel toolchain — which is the standard environment on ISSP supercomputers (e.g. kugui) and the intended platform for the ELPA multi-node FullDiag path. Encountered while rebuilding on kugui (Intel oneAPI 2022 + Intel MPI 2021.7) for the ELPA FullDiag phase-3 benchmarks.

**Suggested fix (any one):**
- Drop the `ONLY` clause: `USE mpi` (simplest; matches the pre-5bee7b45 style if it used mpif.h/plain USE).
- Or revert to `include 'mpif.h'` for these four routines.
- Or guard the module symbols the way Intel MPI expects.

Please verify the chosen fix compiles under BOTH GNU+OpenMPI and Intel+IntelMPI. Low-risk, isolated to the four `USE mpi, ONLY` lines in komega_math.F90.

**Comment by k-yoshimi** [comment]
### Observed symptom (reproduction detail)

**Environment:** ISSP supercomputer *kugui*, Intel oneAPI 2022.2.1 (classic `ifort`/`icc`) + Intel MPI 2021.7.1, CMake build of HPhi with `-DUSE_ELPA=ON` (which forces `USE_SCALAPACK=ON` and `MPI`). RHEL 8 / glibc 2.28. The same tree builds cleanly on a GNU host (gcc 13 + Open MPI 5), so the failure is Intel-Fortran-specific and invisible to gcc-based CI.

**Build failure (verbatim):**
```
komega_math.F90(81): error #6580: Name in only-list does not exist or is not accessible.   [MPI_ALLREDUCE]
  USE mpi, ONLY : MPI_Allreduce, MPI_DOUBLE_PRECISION, MPI_SUM
------------------^
komega_math.F90(113): error #6580: ... [MPI_ALLREDUCE]
komega_math.F90(151): error #6580: ... [MPI_ALLREDUCE]
komega_math.F90(187): error #6580: ... [MPI_ALLREDUCE]
compilation aborted for .../src/komega/komega_math.F90 (code 1)
gmake: *** [Makefile:179: HPhi] Error 2
```
The build aborts at the `komega` target, so no `HPhi` binary is produced — HPhi is entirely unbuildable with the Intel toolchain.

**Precise trigger.** Commit `5bee7b45` ("Harden Komega MPI scalar reductions") changed the four `ONLY` lists from a constant to a subroutine name:
```diff
-  use mpi, only : MPI_IN_PLACE, MPI_DOUBLE_PRECISION, MPI_SUM
+  USE mpi, ONLY : MPI_Allreduce, MPI_DOUBLE_PRECISION, MPI_SUM
```
`MPI_IN_PLACE`, `MPI_SUM`, `MPI_DOUBLE_PRECISION`, `MPI_MAX`, `MPI_DOUBLE_COMPLEX` are **named constants** and Intel's `mpi` module makes them accessible through an `ONLY` clause. `MPI_Allreduce`, however, is a **generic subroutine interface** in the `mpi` module, and Intel Fortran does not allow a generic interface to be named in an `ONLY` list (hence #6580) — whereas GNU Fortran does. So it is specifically the addition of `MPI_Allreduce` to the `ONLY` list (lines 81/113/151/187) that breaks the Intel build; the constants on the same lines are fine.

**Impact.** This blocks every Intel-toolchain build, which is the standard environment on the ISSP supercomputers (kugui, etc.) — the intended platform for the ELPA multi-node FullDiag path. It surfaced while rebuilding on kugui to refresh the ELPA FullDiag phase-3 benchmarks (PR #276); those kugui benchmarks are deferred until this is fixed.

**Fix options (any one; please verify under BOTH GNU+OpenMPI and Intel+IntelMPI):**
- Drop `MPI_Allreduce` from the `ONLY` list, keeping only the constants — e.g. `USE mpi, ONLY : MPI_DOUBLE_PRECISION, MPI_SUM` — since the `MPI_Allreduce` call resolved without being in the `ONLY` list before `5bee7b45`.
- Or use plain `USE mpi` (no `ONLY`) for these four routines.
- Or revert to `include 'mpif.h'`.

**Comment by k-yoshimi** [comment]
Fixed by #292: all four `USE mpi, ONLY : MPI_Allreduce, ...` clauses in `src/komega/komega_math.F90` (lines 81/113/151/187) are now plain `USE mpi`, which both GNU and Intel Fortran accept — verified on current `develop`. Intel-toolchain (kugui) builds are unblocked.
